#!/bin/bash
DOCKERFILE=Dockerfile
TAG=frontend-latest
TIMESTAMP=`date +"%Y%m%d%H%M%S"`
docker build -f $DOCKERFILE --pull --force-rm=true --rm=true --build-arg TIMESTAMP=$TIMESTAMP -t apendergast/hm-docker-base:$TAG .
